export enum ItemType {
  COMMON_ITEM_INSTANCE = 'COMMON_ITEM_INSTANCE',
  HELMET_ITEM_INSTANCE = 'HELMET_ITEM_INSTANCE',
  CHEST_ITEM_INSTANCE = 'CHEST_ITEM_INSTANCE',
  ARMOR_ITEM_INSTANCE = 'ARMOR_ITEM_INSTANCE',
  GLOVES_ITEM_INSTANCE = 'GLOVES_ITEM_INSTANCE',
  BOOTS_ITEM_INSTANCE = 'BOOTS_ITEM_INSTANCE',
}
