export enum ItemStatType {

  BONUS_HEALTH = 'BONUS_HEALTH',
  BONUS_ARMOR = 'BONUS_ARMOR',
  BONUS_DAMAGE = 'BONUS_DAMAGE',
  ATTACK_SPEED = 'ATTACK_SPEED',
  CRIT_CHANCE = 'CRIT_CHANCE',
  LIFESTEAL = 'LIFESTEAL',

}
