export enum ItemStatTypeEnum {

  BONUS_HEALTH = 'BONUS_HEALTH',
  BONUS_ARMOR = 'BONUS_ARMOR',
  BONUS_DAMAGE = 'BONUS_DAMAGE',
  ATTACK_SPEED = 'ATTACK_SPEED',
  CRITICAL_CHANCE = 'CRITICAL_CHANCE',
  CRITICAL_DAMAGE = 'CRITICAL_DAMAGE',
  LIFESTEAL = 'LIFESTEAL',

}
